// Code generated by MockGen. DO NOT EDIT.
// Source: webapp/backend/pkg/database/interface.go

// Package mock_database is a generated GoMock package.
package mock_database

import (
	context "context"
	reflect "reflect"
	time "time"

	pkg "github.com/analogj/scrutiny/webapp/backend/pkg"
	database "github.com/analogj/scrutiny/webapp/backend/pkg/database"
	models "github.com/analogj/scrutiny/webapp/backend/pkg/models"
	collector "github.com/analogj/scrutiny/webapp/backend/pkg/models/collector"
	measurements "github.com/analogj/scrutiny/webapp/backend/pkg/models/measurements"
	overrides "github.com/analogj/scrutiny/webapp/backend/pkg/overrides"
	gomock "github.com/golang/mock/gomock"
)

// MockDeviceRepo is a mock of DeviceRepo interface.
type MockDeviceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceRepoMockRecorder
}

// MockDeviceRepoMockRecorder is the mock recorder for MockDeviceRepo.
type MockDeviceRepoMockRecorder struct {
	mock *MockDeviceRepo
}

// NewMockDeviceRepo creates a new mock instance.
func NewMockDeviceRepo(ctrl *gomock.Controller) *MockDeviceRepo {
	mock := &MockDeviceRepo{ctrl: ctrl}
	mock.recorder = &MockDeviceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceRepo) EXPECT() *MockDeviceRepoMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDeviceRepo) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDeviceRepoMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDeviceRepo)(nil).Close))
}

// DeleteAttributeOverride mocks base method.
func (m *MockDeviceRepo) DeleteAttributeOverride(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttributeOverride", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAttributeOverride indicates an expected call of DeleteAttributeOverride.
func (mr *MockDeviceRepoMockRecorder) DeleteAttributeOverride(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttributeOverride", reflect.TypeOf((*MockDeviceRepo)(nil).DeleteAttributeOverride), ctx, id)
}

// DeleteDevice mocks base method.
func (m *MockDeviceRepo) DeleteDevice(ctx context.Context, deviceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDevice", ctx, deviceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDevice indicates an expected call of DeleteDevice.
func (mr *MockDeviceRepoMockRecorder) DeleteDevice(ctx, deviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDevice", reflect.TypeOf((*MockDeviceRepo)(nil).DeleteDevice), ctx, deviceID)
}

// DeleteZFSPool mocks base method.
func (m *MockDeviceRepo) DeleteZFSPool(ctx context.Context, guid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteZFSPool", ctx, guid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteZFSPool indicates an expected call of DeleteZFSPool.
func (mr *MockDeviceRepoMockRecorder) DeleteZFSPool(ctx, guid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteZFSPool", reflect.TypeOf((*MockDeviceRepo)(nil).DeleteZFSPool), ctx, guid)
}

// GetAttributeOverrideByID mocks base method.
func (m *MockDeviceRepo) GetAttributeOverrideByID(ctx context.Context, id uint) (*models.AttributeOverride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttributeOverrideByID", ctx, id)
	ret0, _ := ret[0].(*models.AttributeOverride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttributeOverrideByID indicates an expected call of GetAttributeOverrideByID.
func (mr *MockDeviceRepoMockRecorder) GetAttributeOverrideByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttributeOverrideByID", reflect.TypeOf((*MockDeviceRepo)(nil).GetAttributeOverrideByID), ctx, id)
}

// GetAttributeOverrides mocks base method.
func (m *MockDeviceRepo) GetAttributeOverrides(ctx context.Context) ([]models.AttributeOverride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttributeOverrides", ctx)
	ret0, _ := ret[0].([]models.AttributeOverride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttributeOverrides indicates an expected call of GetAttributeOverrides.
func (mr *MockDeviceRepoMockRecorder) GetAttributeOverrides(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttributeOverrides", reflect.TypeOf((*MockDeviceRepo)(nil).GetAttributeOverrides), ctx)
}

// GetAllOverridesForDisplay mocks base method.
func (m *MockDeviceRepo) GetAllOverridesForDisplay(ctx context.Context) ([]models.AttributeOverride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOverridesForDisplay", ctx)
	ret0, _ := ret[0].([]models.AttributeOverride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOverridesForDisplay indicates an expected call of GetAllOverridesForDisplay.
func (mr *MockDeviceRepoMockRecorder) GetAllOverridesForDisplay(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOverridesForDisplay", reflect.TypeOf((*MockDeviceRepo)(nil).GetAllOverridesForDisplay), ctx)
}

// GetAvailableInfluxDBBuckets mocks base method.
func (m *MockDeviceRepo) GetAvailableInfluxDBBuckets(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableInfluxDBBuckets", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableInfluxDBBuckets indicates an expected call of GetAvailableInfluxDBBuckets.
func (mr *MockDeviceRepoMockRecorder) GetAvailableInfluxDBBuckets(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableInfluxDBBuckets", reflect.TypeOf((*MockDeviceRepo)(nil).GetAvailableInfluxDBBuckets), ctx)
}

// GetDeviceDetails mocks base method.
func (m *MockDeviceRepo) GetDeviceDetails(ctx context.Context, deviceID string) (models.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceDetails", ctx, deviceID)
	ret0, _ := ret[0].(models.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceDetails indicates an expected call of GetDeviceDetails.
func (mr *MockDeviceRepoMockRecorder) GetDeviceDetails(ctx, deviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceDetails", reflect.TypeOf((*MockDeviceRepo)(nil).GetDeviceDetails), ctx, deviceID)
}

// GetDeviceByID mocks base method.
func (m *MockDeviceRepo) GetDeviceByID(ctx context.Context, deviceID string) (models.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceByID", ctx, deviceID)
	ret0, _ := ret[0].(models.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceByID indicates an expected call of GetDeviceByID.
func (mr *MockDeviceRepoMockRecorder) GetDeviceByID(ctx, deviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceByID", reflect.TypeOf((*MockDeviceRepo)(nil).GetDeviceByID), ctx, deviceID)
}

// GetDeviceByWWN mocks base method.
func (m *MockDeviceRepo) GetDeviceByWWN(ctx context.Context, wwn string) (models.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceByWWN", ctx, wwn)
	ret0, _ := ret[0].(models.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceByWWN indicates an expected call of GetDeviceByWWN.
func (mr *MockDeviceRepoMockRecorder) GetDeviceByWWN(ctx, wwn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceByWWN", reflect.TypeOf((*MockDeviceRepo)(nil).GetDeviceByWWN), ctx, wwn)
}

// GetDevices mocks base method.
func (m *MockDeviceRepo) GetDevices(ctx context.Context) ([]models.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevices", ctx)
	ret0, _ := ret[0].([]models.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevices indicates an expected call of GetDevices.
func (mr *MockDeviceRepoMockRecorder) GetDevices(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevices", reflect.TypeOf((*MockDeviceRepo)(nil).GetDevices), ctx)
}

// GetSortedDevices mocks base method.
func (m *MockDeviceRepo) GetSortedDevices(ctx context.Context) ([]models.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSortedDevices", ctx)
	ret0, _ := ret[0].([]models.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSortedDevices indicates an expected call of GetDevices.
func (mr *MockDeviceRepoMockRecorder) GetSortedDevices(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSortedDevices", reflect.TypeOf((*MockDeviceRepo)(nil).GetDevices), ctx)
}

// GetDevicesLastSeenTimes mocks base method.
func (m *MockDeviceRepo) GetDevicesLastSeenTimes(ctx context.Context) (map[string]time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevicesLastSeenTimes", ctx)
	ret0, _ := ret[0].(map[string]time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevicesLastSeenTimes indicates an expected call of GetDevicesLastSeenTimes.
func (mr *MockDeviceRepoMockRecorder) GetDevicesLastSeenTimes(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevicesLastSeenTimes", reflect.TypeOf((*MockDeviceRepo)(nil).GetDevicesLastSeenTimes), ctx)
}

// MergeDevices mocks base method.
func (m *MockDeviceRepo) MergeDevices(ctx context.Context, sourceDeviceID, destinationDeviceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeDevices", ctx, sourceDeviceID, destinationDeviceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeDevices indicates an expected call of MergeDevices.
func (mr *MockDeviceRepoMockRecorder) MergeDevices(ctx, sourceDeviceID, destinationDeviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeDevices", reflect.TypeOf((*MockDeviceRepo)(nil).MergeDevices), ctx, sourceDeviceID, destinationDeviceID)
}

// GetLatestSmartSubmission mocks base method.
func (m *MockDeviceRepo) GetLatestSmartSubmission(ctx context.Context, wwn string) ([]measurements.Smart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestSmartSubmission", ctx, wwn)
	ret0, _ := ret[0].([]measurements.Smart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestSmartSubmission indicates an expected call of GetLatestSmartSubmission.
func (mr *MockDeviceRepoMockRecorder) GetLatestSmartSubmission(ctx, wwn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestSmartSubmission", reflect.TypeOf((*MockDeviceRepo)(nil).GetLatestSmartSubmission), ctx, wwn)
}

// DeleteBtrfsFilesystem mocks base method.
func (m *MockDeviceRepo) DeleteBtrfsFilesystem(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBtrfsFilesystem", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBtrfsFilesystem indicates an expected call of DeleteBtrfsFilesystem.
func (mr *MockDeviceRepoMockRecorder) DeleteBtrfsFilesystem(ctx, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBtrfsFilesystem", reflect.TypeOf((*MockDeviceRepo)(nil).DeleteBtrfsFilesystem), ctx, uuid)
}

// GetBtrfsFilesystemDetails mocks base method.
func (m *MockDeviceRepo) GetBtrfsFilesystemDetails(ctx context.Context, uuid string) (models.BtrfsFilesystem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBtrfsFilesystemDetails", ctx, uuid)
	ret0, _ := ret[0].(models.BtrfsFilesystem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBtrfsFilesystemDetails indicates an expected call of GetBtrfsFilesystemDetails.
func (mr *MockDeviceRepoMockRecorder) GetBtrfsFilesystemDetails(ctx, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBtrfsFilesystemDetails", reflect.TypeOf((*MockDeviceRepo)(nil).GetBtrfsFilesystemDetails), ctx, uuid)
}

// GetBtrfsFilesystems mocks base method.
func (m *MockDeviceRepo) GetBtrfsFilesystems(ctx context.Context) ([]models.BtrfsFilesystem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBtrfsFilesystems", ctx)
	ret0, _ := ret[0].([]models.BtrfsFilesystem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBtrfsFilesystems indicates an expected call of GetBtrfsFilesystems.
func (mr *MockDeviceRepoMockRecorder) GetBtrfsFilesystems(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBtrfsFilesystems", reflect.TypeOf((*MockDeviceRepo)(nil).GetBtrfsFilesystems), ctx)
}

// GetBtrfsFilesystemsSummary mocks base method.
func (m *MockDeviceRepo) GetBtrfsFilesystemsSummary(ctx context.Context) (map[string]*models.BtrfsFilesystem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBtrfsFilesystemsSummary", ctx)
	ret0, _ := ret[0].(map[string]*models.BtrfsFilesystem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBtrfsFilesystemsSummary indicates an expected call of GetBtrfsFilesystemsSummary.
func (mr *MockDeviceRepoMockRecorder) GetBtrfsFilesystemsSummary(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBtrfsFilesystemsSummary", reflect.TypeOf((*MockDeviceRepo)(nil).GetBtrfsFilesystemsSummary), ctx)
}

// GetBtrfsMetricsHistory mocks base method.
func (m *MockDeviceRepo) GetBtrfsMetricsHistory(ctx context.Context, uuid, durationKey string) ([]measurements.BtrfsMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBtrfsMetricsHistory", ctx, uuid, durationKey)
	ret0, _ := ret[0].([]measurements.BtrfsMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBtrfsMetricsHistory indicates an expected call of GetBtrfsMetricsHistory.
func (mr *MockDeviceRepoMockRecorder) GetBtrfsMetricsHistory(ctx, uuid, durationKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBtrfsMetricsHistory", reflect.TypeOf((*MockDeviceRepo)(nil).GetBtrfsMetricsHistory), ctx, uuid, durationKey)
}

// RegisterBtrfsFilesystem mocks base method.
func (m *MockDeviceRepo) RegisterBtrfsFilesystem(ctx context.Context, filesystem *models.BtrfsFilesystem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterBtrfsFilesystem", ctx, filesystem)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterBtrfsFilesystem indicates an expected call of RegisterBtrfsFilesystem.
func (mr *MockDeviceRepoMockRecorder) RegisterBtrfsFilesystem(ctx, filesystem interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterBtrfsFilesystem", reflect.TypeOf((*MockDeviceRepo)(nil).RegisterBtrfsFilesystem), ctx, filesystem)
}

// SaveBtrfsMetrics mocks base method.
func (m *MockDeviceRepo) SaveBtrfsMetrics(ctx context.Context, filesystem *models.BtrfsFilesystem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBtrfsMetrics", ctx, filesystem)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBtrfsMetrics indicates an expected call of SaveBtrfsMetrics.
func (mr *MockDeviceRepoMockRecorder) SaveBtrfsMetrics(ctx, filesystem interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBtrfsMetrics", reflect.TypeOf((*MockDeviceRepo)(nil).SaveBtrfsMetrics), ctx, filesystem)
}

// UpdateBtrfsFilesystemArchived mocks base method.
func (m *MockDeviceRepo) UpdateBtrfsFilesystemArchived(ctx context.Context, uuid string, archived bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBtrfsFilesystemArchived", ctx, uuid, archived)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBtrfsFilesystemArchived indicates an expected call of UpdateBtrfsFilesystemArchived.
func (mr *MockDeviceRepoMockRecorder) UpdateBtrfsFilesystemArchived(ctx, uuid, archived interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBtrfsFilesystemArchived", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateBtrfsFilesystemArchived), ctx, uuid, archived)
}

// UpdateBtrfsFilesystemLabel mocks base method.
func (m *MockDeviceRepo) UpdateBtrfsFilesystemLabel(ctx context.Context, uuid, label string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBtrfsFilesystemLabel", ctx, uuid, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBtrfsFilesystemLabel indicates an expected call of UpdateBtrfsFilesystemLabel.
func (mr *MockDeviceRepoMockRecorder) UpdateBtrfsFilesystemLabel(ctx, uuid, label interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBtrfsFilesystemLabel", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateBtrfsFilesystemLabel), ctx, uuid, label)
}

// UpdateBtrfsFilesystemMuted mocks base method.
func (m *MockDeviceRepo) UpdateBtrfsFilesystemMuted(ctx context.Context, uuid string, muted bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBtrfsFilesystemMuted", ctx, uuid, muted)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBtrfsFilesystemMuted indicates an expected call of UpdateBtrfsFilesystemMuted.
func (mr *MockDeviceRepoMockRecorder) UpdateBtrfsFilesystemMuted(ctx, uuid, muted interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBtrfsFilesystemMuted", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateBtrfsFilesystemMuted), ctx, uuid, muted)
}

// GetMergedOverrides mocks base method.
func (m *MockDeviceRepo) GetMergedOverrides(ctx context.Context) []overrides.AttributeOverride {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMergedOverrides", ctx)
	ret0, _ := ret[0].([]overrides.AttributeOverride)
	return ret0
}

// GetMergedOverrides indicates an expected call of GetMergedOverrides.
func (mr *MockDeviceRepoMockRecorder) GetMergedOverrides(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMergedOverrides", reflect.TypeOf((*MockDeviceRepo)(nil).GetMergedOverrides), ctx)
}

// GetPerformanceBaseline mocks base method.
func (m *MockDeviceRepo) GetPerformanceBaseline(ctx context.Context, wwn string, count int) (*measurements.PerformanceBaseline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPerformanceBaseline", ctx, wwn, count)
	ret0, _ := ret[0].(*measurements.PerformanceBaseline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPerformanceBaseline indicates an expected call of GetPerformanceBaseline.
func (mr *MockDeviceRepoMockRecorder) GetPerformanceBaseline(ctx, wwn, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPerformanceBaseline", reflect.TypeOf((*MockDeviceRepo)(nil).GetPerformanceBaseline), ctx, wwn, count)
}

// GetPerformanceHistory mocks base method.
func (m *MockDeviceRepo) GetPerformanceHistory(ctx context.Context, wwn, durationKey string) ([]measurements.Performance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPerformanceHistory", ctx, wwn, durationKey)
	ret0, _ := ret[0].([]measurements.Performance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPerformanceHistory indicates an expected call of GetPerformanceHistory.
func (mr *MockDeviceRepoMockRecorder) GetPerformanceHistory(ctx, wwn, durationKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPerformanceHistory", reflect.TypeOf((*MockDeviceRepo)(nil).GetPerformanceHistory), ctx, wwn, durationKey)
}

// GetPreviousSmartSubmission mocks base method.
func (m *MockDeviceRepo) GetPreviousSmartSubmission(ctx context.Context, wwn string) ([]measurements.Smart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreviousSmartSubmission", ctx, wwn)
	ret0, _ := ret[0].([]measurements.Smart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreviousSmartSubmission indicates an expected call of GetPreviousSmartSubmission.
func (mr *MockDeviceRepoMockRecorder) GetPreviousSmartSubmission(ctx, wwn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreviousSmartSubmission", reflect.TypeOf((*MockDeviceRepo)(nil).GetPreviousSmartSubmission), ctx, wwn)
}

// GetSettingValue mocks base method.
func (m *MockDeviceRepo) GetSettingValue(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettingValue", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettingValue indicates an expected call of GetSettingValue.
func (mr *MockDeviceRepoMockRecorder) GetSettingValue(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettingValue", reflect.TypeOf((*MockDeviceRepo)(nil).GetSettingValue), ctx, key)
}

// GetSmartAttributeHistory mocks base method.
func (m *MockDeviceRepo) GetSmartAttributeHistory(ctx context.Context, wwn, durationKey string, selectEntries, selectEntriesOffset int, attributes []string) ([]measurements.Smart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSmartAttributeHistory", ctx, wwn, durationKey, selectEntries, selectEntriesOffset, attributes)
	ret0, _ := ret[0].([]measurements.Smart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSmartAttributeHistory indicates an expected call of GetSmartAttributeHistory.
func (mr *MockDeviceRepoMockRecorder) GetSmartAttributeHistory(ctx, wwn, durationKey, selectEntries, selectEntriesOffset, attributes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSmartAttributeHistory", reflect.TypeOf((*MockDeviceRepo)(nil).GetSmartAttributeHistory), ctx, wwn, durationKey, selectEntries, selectEntriesOffset, attributes)
}

// GetSmartTemperatureHistory mocks base method.
func (m *MockDeviceRepo) GetSmartTemperatureHistory(ctx context.Context, durationKey string) (map[string][]measurements.SmartTemperature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSmartTemperatureHistory", ctx, durationKey)
	ret0, _ := ret[0].(map[string][]measurements.SmartTemperature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSmartTemperatureHistory indicates an expected call of GetSmartTemperatureHistory.
func (mr *MockDeviceRepoMockRecorder) GetSmartTemperatureHistory(ctx, durationKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSmartTemperatureHistory", reflect.TypeOf((*MockDeviceRepo)(nil).GetSmartTemperatureHistory), ctx, durationKey)
}

// SaveFilesystemSummary mocks base method.
func (m *MockDeviceRepo) SaveFilesystemSummary(ctx context.Context, payload models.FilesystemSummaryUpload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFilesystemSummary", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFilesystemSummary indicates an expected call of SaveFilesystemSummary.
func (mr *MockDeviceRepoMockRecorder) SaveFilesystemSummary(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFilesystemSummary", reflect.TypeOf((*MockDeviceRepo)(nil).SaveFilesystemSummary), ctx, payload)
}

// GetFilesystemSummary mocks base method.
func (m *MockDeviceRepo) GetFilesystemSummary(ctx context.Context) (map[string][]models.FilesystemCapacity, map[string]*models.FilesystemHostStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilesystemSummary", ctx)
	ret0, _ := ret[0].(map[string][]models.FilesystemCapacity)
	ret1, _ := ret[1].(map[string]*models.FilesystemHostStatus)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFilesystemSummary indicates an expected call of GetFilesystemSummary.
func (mr *MockDeviceRepoMockRecorder) GetFilesystemSummary(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilesystemSummary", reflect.TypeOf((*MockDeviceRepo)(nil).GetFilesystemSummary), ctx)
}

// GetSummary mocks base method.
func (m *MockDeviceRepo) GetSummary(ctx context.Context) (map[string]*models.DeviceSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx)
	ret0, _ := ret[0].(map[string]*models.DeviceSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockDeviceRepoMockRecorder) GetSummary(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockDeviceRepo)(nil).GetSummary), ctx)
}

// GetWorkloadInsights mocks base method.
func (m *MockDeviceRepo) GetWorkloadInsights(ctx context.Context, durationKey string) (map[string]*models.WorkloadInsight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkloadInsights", ctx, durationKey)
	ret0, _ := ret[0].(map[string]*models.WorkloadInsight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkloadInsights indicates an expected call of GetWorkloadInsights.
func (mr *MockDeviceRepoMockRecorder) GetWorkloadInsights(ctx, durationKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkloadInsights", reflect.TypeOf((*MockDeviceRepo)(nil).GetWorkloadInsights), ctx, durationKey)
}

// GetZFSPoolDetails mocks base method.
func (m *MockDeviceRepo) GetZFSPoolDetails(ctx context.Context, guid string) (models.ZFSPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZFSPoolDetails", ctx, guid)
	ret0, _ := ret[0].(models.ZFSPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetZFSPoolDetails indicates an expected call of GetZFSPoolDetails.
func (mr *MockDeviceRepoMockRecorder) GetZFSPoolDetails(ctx, guid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZFSPoolDetails", reflect.TypeOf((*MockDeviceRepo)(nil).GetZFSPoolDetails), ctx, guid)
}

// GetZFSPoolMetricsHistory mocks base method.
func (m *MockDeviceRepo) GetZFSPoolMetricsHistory(ctx context.Context, guid, durationKey string) ([]measurements.ZFSPoolMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZFSPoolMetricsHistory", ctx, guid, durationKey)
	ret0, _ := ret[0].([]measurements.ZFSPoolMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetZFSPoolMetricsHistory indicates an expected call of GetZFSPoolMetricsHistory.
func (mr *MockDeviceRepoMockRecorder) GetZFSPoolMetricsHistory(ctx, guid, durationKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZFSPoolMetricsHistory", reflect.TypeOf((*MockDeviceRepo)(nil).GetZFSPoolMetricsHistory), ctx, guid, durationKey)
}

// GetZFSPools mocks base method.
func (m *MockDeviceRepo) GetZFSPools(ctx context.Context) ([]models.ZFSPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZFSPools", ctx)
	ret0, _ := ret[0].([]models.ZFSPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetZFSPools indicates an expected call of GetZFSPools.
func (mr *MockDeviceRepoMockRecorder) GetZFSPools(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZFSPools", reflect.TypeOf((*MockDeviceRepo)(nil).GetZFSPools), ctx)
}

// GetZFSPoolsSummary mocks base method.
func (m *MockDeviceRepo) GetZFSPoolsSummary(ctx context.Context) (map[string]*models.ZFSPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZFSPoolsSummary", ctx)
	ret0, _ := ret[0].(map[string]*models.ZFSPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetZFSPoolsSummary indicates an expected call of GetZFSPoolsSummary.
func (mr *MockDeviceRepoMockRecorder) GetZFSPoolsSummary(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZFSPoolsSummary", reflect.TypeOf((*MockDeviceRepo)(nil).GetZFSPoolsSummary), ctx)
}

// HealthCheck mocks base method.
func (m *MockDeviceRepo) HealthCheck(ctx context.Context) (*database.HealthCheckResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(*database.HealthCheckResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockDeviceRepoMockRecorder) HealthCheck(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockDeviceRepo)(nil).HealthCheck), ctx)
}

// LoadSettings mocks base method.
func (m *MockDeviceRepo) LoadSettings(ctx context.Context) (*models.Settings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadSettings", ctx)
	ret0, _ := ret[0].(*models.Settings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadSettings indicates an expected call of LoadSettings.
func (mr *MockDeviceRepoMockRecorder) LoadSettings(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadSettings", reflect.TypeOf((*MockDeviceRepo)(nil).LoadSettings), ctx)
}

// RecalculateDeviceStatusFromHistory mocks base method.
func (m *MockDeviceRepo) RecalculateDeviceStatusFromHistory(ctx context.Context, deviceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecalculateDeviceStatusFromHistory", ctx, deviceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecalculateDeviceStatusFromHistory indicates an expected call of RecalculateDeviceStatusFromHistory.
func (mr *MockDeviceRepoMockRecorder) RecalculateDeviceStatusFromHistory(ctx, deviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecalculateDeviceStatusFromHistory", reflect.TypeOf((*MockDeviceRepo)(nil).RecalculateDeviceStatusFromHistory), ctx, deviceID)
}

// RegisterDevice mocks base method.
func (m *MockDeviceRepo) RegisterDevice(ctx context.Context, dev models.Device) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterDevice", ctx, dev)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterDevice indicates an expected call of RegisterDevice.
func (mr *MockDeviceRepoMockRecorder) RegisterDevice(ctx, dev interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterDevice", reflect.TypeOf((*MockDeviceRepo)(nil).RegisterDevice), ctx, dev)
}

// RegisterZFSPool mocks base method.
func (m *MockDeviceRepo) RegisterZFSPool(ctx context.Context, pool models.ZFSPool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterZFSPool", ctx, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterZFSPool indicates an expected call of RegisterZFSPool.
func (mr *MockDeviceRepoMockRecorder) RegisterZFSPool(ctx, pool interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterZFSPool", reflect.TypeOf((*MockDeviceRepo)(nil).RegisterZFSPool), ctx, pool)
}

// ResetDeviceStatus mocks base method.
func (m *MockDeviceRepo) ResetDeviceStatus(ctx context.Context, deviceID string) (models.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetDeviceStatus", ctx, deviceID)
	ret0, _ := ret[0].(models.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetDeviceStatus indicates an expected call of ResetDeviceStatus.
func (mr *MockDeviceRepoMockRecorder) ResetDeviceStatus(ctx, deviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetDeviceStatus", reflect.TypeOf((*MockDeviceRepo)(nil).ResetDeviceStatus), ctx, deviceID)
}

// SaveAttributeOverride mocks base method.
func (m *MockDeviceRepo) SaveAttributeOverride(ctx context.Context, override *models.AttributeOverride) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAttributeOverride", ctx, override)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAttributeOverride indicates an expected call of SaveAttributeOverride.
func (mr *MockDeviceRepoMockRecorder) SaveAttributeOverride(ctx, override interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAttributeOverride", reflect.TypeOf((*MockDeviceRepo)(nil).SaveAttributeOverride), ctx, override)
}

// SavePerformanceResults mocks base method.
func (m *MockDeviceRepo) SavePerformanceResults(ctx context.Context, wwn string, perfData *measurements.Performance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePerformanceResults", ctx, wwn, perfData)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePerformanceResults indicates an expected call of SavePerformanceResults.
func (mr *MockDeviceRepoMockRecorder) SavePerformanceResults(ctx, wwn, perfData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePerformanceResults", reflect.TypeOf((*MockDeviceRepo)(nil).SavePerformanceResults), ctx, wwn, perfData)
}

// SaveSettings mocks base method.
func (m *MockDeviceRepo) SaveSettings(ctx context.Context, settings models.Settings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSettings", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSettings indicates an expected call of SaveSettings.
func (mr *MockDeviceRepoMockRecorder) SaveSettings(ctx, settings interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSettings", reflect.TypeOf((*MockDeviceRepo)(nil).SaveSettings), ctx, settings)
}

// SaveSmartAttributes mocks base method.
func (m *MockDeviceRepo) SaveSmartAttributes(ctx context.Context, wwn string, collectorSmartData collector.SmartInfo) (measurements.Smart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSmartAttributes", ctx, wwn, collectorSmartData)
	ret0, _ := ret[0].(measurements.Smart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveSmartAttributes indicates an expected call of SaveSmartAttributes.
func (mr *MockDeviceRepoMockRecorder) SaveSmartAttributes(ctx, wwn, collectorSmartData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSmartAttributes", reflect.TypeOf((*MockDeviceRepo)(nil).SaveSmartAttributes), ctx, wwn, collectorSmartData)
}

// SaveSmartTemperature mocks base method.
func (m *MockDeviceRepo) SaveSmartTemperature(ctx context.Context, wwn string, deviceID string, collectorSmartData *collector.SmartInfo, retrieveSCTTemperatureHistory bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSmartTemperature", ctx, wwn, deviceID, collectorSmartData, retrieveSCTTemperatureHistory)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSmartTemperature indicates an expected call of SaveSmartTemperature.
func (mr *MockDeviceRepoMockRecorder) SaveSmartTemperature(ctx, wwn, deviceID, collectorSmartData, retrieveSCTTemperatureHistory interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSmartTemperature", reflect.TypeOf((*MockDeviceRepo)(nil).SaveSmartTemperature), ctx, wwn, deviceID, collectorSmartData, retrieveSCTTemperatureHistory)
}

// SaveZFSPoolMetrics mocks base method.
func (m *MockDeviceRepo) SaveZFSPoolMetrics(ctx context.Context, pool models.ZFSPool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveZFSPoolMetrics", ctx, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveZFSPoolMetrics indicates an expected call of SaveZFSPoolMetrics.
func (mr *MockDeviceRepoMockRecorder) SaveZFSPoolMetrics(ctx, pool interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveZFSPoolMetrics", reflect.TypeOf((*MockDeviceRepo)(nil).SaveZFSPoolMetrics), ctx, pool)
}

// SetSettingValue mocks base method.
func (m *MockDeviceRepo) SetSettingValue(ctx context.Context, key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSettingValue", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSettingValue indicates an expected call of SetSettingValue.
func (mr *MockDeviceRepoMockRecorder) SetSettingValue(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSettingValue", reflect.TypeOf((*MockDeviceRepo)(nil).SetSettingValue), ctx, key, value)
}

// UpdateDevice mocks base method.
func (m *MockDeviceRepo) UpdateDevice(ctx context.Context, deviceID string, collectorSmartData *collector.SmartInfo) (models.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDevice", ctx, deviceID, collectorSmartData)
	ret0, _ := ret[0].(models.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDevice indicates an expected call of UpdateDevice.
func (mr *MockDeviceRepoMockRecorder) UpdateDevice(ctx, deviceID, collectorSmartData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDevice", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateDevice), ctx, deviceID, collectorSmartData)
}

// UpdateDeviceArchived mocks base method.
func (m *MockDeviceRepo) UpdateDeviceArchived(ctx context.Context, deviceID string, archived bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceArchived", ctx, deviceID, archived)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeviceArchived indicates an expected call of UpdateDeviceArchived.
func (mr *MockDeviceRepoMockRecorder) UpdateDeviceArchived(ctx, deviceID, archived interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceArchived", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateDeviceArchived), ctx, deviceID, archived)
}

// UpdateDeviceHasForcedFailure mocks base method.
func (m *MockDeviceRepo) UpdateDeviceHasForcedFailure(ctx context.Context, deviceID string, hasForcedFailure bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceHasForcedFailure", ctx, deviceID, hasForcedFailure)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeviceHasForcedFailure indicates an expected call of UpdateDeviceHasForcedFailure.
func (mr *MockDeviceRepoMockRecorder) UpdateDeviceHasForcedFailure(ctx, deviceID, hasForcedFailure interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceHasForcedFailure", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateDeviceHasForcedFailure), ctx, deviceID, hasForcedFailure)
}

// UpdateDeviceMissedPingTimeout mocks base method.
func (m *MockDeviceRepo) UpdateDeviceMissedPingTimeout(ctx context.Context, deviceID string, timeoutMinutes int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceMissedPingTimeout", ctx, deviceID, timeoutMinutes)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeviceMissedPingTimeout indicates an expected call of UpdateDeviceMissedPingTimeout.
func (mr *MockDeviceRepoMockRecorder) UpdateDeviceMissedPingTimeout(ctx, deviceID, timeoutMinutes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceMissedPingTimeout", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateDeviceMissedPingTimeout), ctx, deviceID, timeoutMinutes)
}

// UpdateDeviceLabel mocks base method.
func (m *MockDeviceRepo) UpdateDeviceLabel(ctx context.Context, deviceID, label string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceLabel", ctx, deviceID, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeviceLabel indicates an expected call of UpdateDeviceLabel.
func (mr *MockDeviceRepoMockRecorder) UpdateDeviceLabel(ctx, deviceID, label interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceLabel", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateDeviceLabel), ctx, deviceID, label)
}

// UpdateDeviceMuted mocks base method.
func (m *MockDeviceRepo) UpdateDeviceMuted(ctx context.Context, deviceID string, muted bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceMuted", ctx, deviceID, muted)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeviceMuted indicates an expected call of UpdateDeviceMuted.
func (mr *MockDeviceRepoMockRecorder) UpdateDeviceMuted(ctx, deviceID, muted interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceMuted", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateDeviceMuted), ctx, deviceID, muted)
}

// UpdateDeviceSmartDisplayMode mocks base method.
func (m *MockDeviceRepo) UpdateDeviceSmartDisplayMode(ctx context.Context, deviceID, mode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceSmartDisplayMode", ctx, deviceID, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeviceSmartDisplayMode indicates an expected call of UpdateDeviceSmartDisplayMode.
func (mr *MockDeviceRepoMockRecorder) UpdateDeviceSmartDisplayMode(ctx, deviceID, mode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceSmartDisplayMode", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateDeviceSmartDisplayMode), ctx, deviceID, mode)
}

// UpdateDeviceStatus mocks base method.
func (m *MockDeviceRepo) UpdateDeviceStatus(ctx context.Context, deviceID string, status pkg.DeviceStatus) (models.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceStatus", ctx, deviceID, status)
	ret0, _ := ret[0].(models.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDeviceStatus indicates an expected call of UpdateDeviceStatus.
func (mr *MockDeviceRepoMockRecorder) UpdateDeviceStatus(ctx, deviceID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceStatus", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateDeviceStatus), ctx, deviceID, status)
}

// UpdateZFSPoolArchived mocks base method.
func (m *MockDeviceRepo) UpdateZFSPoolArchived(ctx context.Context, guid string, archived bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateZFSPoolArchived", ctx, guid, archived)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateZFSPoolArchived indicates an expected call of UpdateZFSPoolArchived.
func (mr *MockDeviceRepoMockRecorder) UpdateZFSPoolArchived(ctx, guid, archived interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateZFSPoolArchived", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateZFSPoolArchived), ctx, guid, archived)
}

// UpdateZFSPoolLabel mocks base method.
func (m *MockDeviceRepo) UpdateZFSPoolLabel(ctx context.Context, guid, label string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateZFSPoolLabel", ctx, guid, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateZFSPoolLabel indicates an expected call of UpdateZFSPoolLabel.
func (mr *MockDeviceRepoMockRecorder) UpdateZFSPoolLabel(ctx, guid, label interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateZFSPoolLabel", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateZFSPoolLabel), ctx, guid, label)
}

// UpdateZFSPoolMuted mocks base method.
func (m *MockDeviceRepo) UpdateZFSPoolMuted(ctx context.Context, guid string, muted bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateZFSPoolMuted", ctx, guid, muted)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateZFSPoolMuted indicates an expected call of UpdateZFSPoolMuted.
func (mr *MockDeviceRepoMockRecorder) UpdateZFSPoolMuted(ctx, guid, muted interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateZFSPoolMuted", reflect.TypeOf((*MockDeviceRepo)(nil).UpdateZFSPoolMuted), ctx, guid, muted)
}

// GetNotifyUrls mocks base method.
func (m *MockDeviceRepo) GetNotifyUrls(ctx context.Context) ([]models.NotifyUrl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotifyUrls", ctx)
	ret0, _ := ret[0].([]models.NotifyUrl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotifyUrls indicates an expected call of GetNotifyUrls.
func (mr *MockDeviceRepoMockRecorder) GetNotifyUrls(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotifyUrls", reflect.TypeOf((*MockDeviceRepo)(nil).GetNotifyUrls), ctx)
}

// SaveNotifyUrl mocks base method.
func (m *MockDeviceRepo) SaveNotifyUrl(ctx context.Context, notifyUrl *models.NotifyUrl) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveNotifyUrl", ctx, notifyUrl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveNotifyUrl indicates an expected call of SaveNotifyUrl.
func (mr *MockDeviceRepoMockRecorder) SaveNotifyUrl(ctx, notifyUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveNotifyUrl", reflect.TypeOf((*MockDeviceRepo)(nil).SaveNotifyUrl), ctx, notifyUrl)
}

// DeleteNotifyUrl mocks base method.
func (m *MockDeviceRepo) DeleteNotifyUrl(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNotifyUrl", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNotifyUrl indicates an expected call of DeleteNotifyUrl.
func (mr *MockDeviceRepoMockRecorder) DeleteNotifyUrl(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNotifyUrl", reflect.TypeOf((*MockDeviceRepo)(nil).DeleteNotifyUrl), ctx, id)
}
